shop/catalog/urls.py
from django.urls import path, include

from catalog.views import subcat_detail

app_name = 'catalog'
urlpatterns = [
    path('/<int:pk>/', subcat_detail , name='cat'),

]

shop/main/urls.py
from django.urls import path, include

from .context_processor import current_city
from .views import main_page, new_user, Login, Logout, profile

app_name = 'main'
urlpatterns = [
    path('', main_page.as_view(), name='hello'),
    path('registration/', new_user, name='reg'),
    path('logout/', Logout.as_view(), name='logout'),
    path('login/', Login.as_view(), name='login'),
    path('profile/<int:pk>', profile, name='profile'),
    path('cont/', current_city, name='current'),
]

shop/shop/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include

from django.conf.urls.static import static

from shop import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog', include('catalog.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/catalog/models.py
from django.db import models


# Create your models here.

class Categories(models.Model):
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.category


class SubCategories(models.Model):
    sub_category = models.CharField(max_length=100)
    category_key = models.ForeignKey(Categories, on_delete=models.CASCADE)

    def __str__(self):
        return self.sub_category

shop/main/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.urls import reverse


class City(models.Model):
    city = models.CharField(max_length=200)

    def __str__(self):
        return self.city


class Shop(models.Model):
    name_of_shop = models.CharField(max_length=200)
    street = models.CharField(max_length=200)
    house = models.CharField(max_length=200)
    city = models.ForeignKey(City, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('shop_detail', args={'pk': self.pk})

    def __str__(self):
        return self.name_of_shop

class PersonCabinet(models.Model):
    phone = models.CharField(max_length=12)
    street = models.CharField(max_length=120)
    home = models.CharField(max_length=3)
    date_of_birth = models.DateField()
    users = models.OneToOneField('User', on_delete=models.CASCADE)

shop/main/forms.py
from django import forms
from django.contrib.auth.models import User


class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password','first_name', 'last_name', 'email']

shop/catalog/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import DetailView

from catalog.models import SubCategories


def subcat_detail(request,pk):
    all_sub_cat = SubCategories.objects.filter(category_key_id=pk)
    print(all_sub_cat)
    context = {
        'all_sub_cat':all_sub_cat
    }
    return render(request, 'cat_detail.html', context)

shop/main/views.py
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.sessions.backends.db import SessionStore
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse_lazy
from django.views.generic import ListView

from .context_processor import current_city
from .forms import NewUserForm
from .models import Shop, City


class main_page(ListView):
    def pp(self):
        print(self.__dict__)

    template_name = 'main_page.html'
    model = Shop
    context_object_name = 'objects'


def new_user(request):
    if request.method == 'POST':
        user = NewUserForm(request.POST)
        if user.is_valid():
            new_user = User.objects.create_user(**user.cleaned_data)
            return redirect('main:hello')
    else:
        form = NewUserForm()
        context = {'form': form}
        return render(request, 'registration.html', context)


class Login(LoginView):
    template_name = 'Login.html'

    def get_success_url(self):
        return reverse_lazy('main:hello')


class Logout(LogoutView):
    next_page = "main:hello"


def profile(request, pk):
    return render(request, 'profile.html')

shop/catalog/templates/cat_detail.html
{% extends "main_page.html" %}

{% block sidebar %}
<div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32">
            <use xlink:href="#bootstrap"></use>
        </svg>
        <span class="fs-4">{{all_sub_cat.1.category_key}}</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        {% for i in all_sub_cat %}
        <li class="nav-item">
            <a href="" class="nav-link active" aria-current="page">
<!--                <svg class="bi me-2" width="16" height="16">-->
<!--                    <use xlink:href="#home"></use>-->
<!--                </svg>-->
                {{i.sub_category}}
            </a>
        </li>
        {% endfor %}
    </ul>
    <hr>
{% endblock %}

shop/main/templates/Login.html
{% extends "main_page.html" %}
{% block main %}
{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

<!--<form action="" method="POST">-->
<!--  {% csrf_token %}-->
<!--  <main class="form-signin">-->
<!--    <div class="form-floating">-->
<!--      <input type="text" class="form-control" id="floatingInput" placeholder="name@example.com">-->
<!--      <label for="floatingInput">Логин</label>-->
<!--    </div>-->
<!--    <div class="form-floating">-->
<!--      <input type="password" class="form-control" id="floatingPassword" placeholder="Password">-->
<!--      <label for="floatingPassword">Пароль</label>-->
<!--    </div>-->
<!--</main>-->
{% block sidebar %}
{% endblock %}
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
  <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
</form>
{% endblock %}

shop/main/templates/main_page.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Главная</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">


    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'main:hello' %}" class="nav-link px-2 link-secondary">
            <img src="media/img/main.jpg" width="100px" height="100px">Home</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">About</a></li>
    </ul>

    <div class="col-md-3 text-end">

        {% if user.is_authenticated %}
        <span style="margin:5px">Привет, {{user.username}}!</span>
        <a href="{% url 'main:logout' %}">
            <button type="button" class="btn btn-primary">Выйти</button>
        </a>
        <br>
        <a href="{% url 'main:profile' user.pk %}"><button type="button" class="btn btn-primary">Личный кабинет</button></a>
        {% else %}
        <a href="{% url 'main:login' %}">
            <button type="button" class="btn btn-outline-primary me-2">Войти</button>
        </a>
        <a href="{% url 'main:reg' %}">
            <button type="button" class="btn btn-primary">Зарегистрироваться</button>
        </a>
        {% endif %}
    </div>
</header>
{% block sidebar %}
<div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32">
            <use xlink:href="#bootstrap"></use>
        </svg>
        <span class="fs-4">Каталог</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        {% for i in cat %}
        <li class="nav-item">
            <a href="{% url 'catalog:cat' i.pk %}" class="nav-link active" aria-current="page">
<!--                <svg class="bi me-2" width="16" height="16">-->
<!--                    <use xlink:href="#home"></use>-->
<!--                </svg>-->
                {{i.category}}
            </a>
        </li>
        {% endfor %}
    </ul>
    <hr>
</div>
{% endblock %}
{% block main %}
{% endblock %}
</body>
<h1>
    {{city}}
</h1>
</html>

shop/main/templates/profile.html
{% extends "main_page.html" %}
{% block main %}

{% block sidebar %}
{% endblock %}

{% endblock %}

shop/main/templates/registration.html
{% extends "main_page.html" %}
{% block main %}
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Регистарция</button>
</form>
{% endblock %}